# Generated by Django 4.2.16 on 2025-09-15 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('level', models.CharField(choices=[('debug', '调试'), ('info', '信息'), ('warning', '警告'), ('error', '错误')], default='info', max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('module', models.CharField(max_length=100, verbose_name='模块名称')),
                ('extra_data', models.JSONField(default=dict, verbose_name='额外数据')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
