# Generated by Django 4.2.16 on 2025-09-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoes', '0001_initial'),
        ('blanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('clearance', models.FloatField(default=2.0, verbose_name='间隙要求(mm)')),
                ('threshold', models.CharField(choices=[('min', '严格标准'), ('p10', 'P10标准'), ('p15', 'P15标准'), ('p20', 'P20标准')], default='p15', max_length=10, verbose_name='通过标准')),
                ('enable_scaling', models.BooleanField(default=True, verbose_name='启用自适应缩放')),
                ('enable_multi_start', models.BooleanField(default=True, verbose_name='启用多起点对齐')),
                ('max_scale', models.FloatField(default=1.03, verbose_name='最大缩放比例')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.CharField(blank=True, max_length=200, verbose_name='当前步骤')),
                ('result_data', models.JSONField(default=dict, verbose_name='匹配结果')),
                ('summary_data', models.JSONField(default=dict, verbose_name='汇总数据')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('report_file', models.CharField(blank=True, max_length=500, verbose_name='报告文件路径')),
                ('heatmap_dir', models.CharField(blank=True, max_length=500, verbose_name='热图目录路径')),
                ('selected_categories', models.ManyToManyField(to='blanks.blankcategory', verbose_name='选择的粗胚分类')),
                ('shoe_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.shoemodel', verbose_name='鞋模')),
            ],
            options={
                'verbose_name': '匹配任务',
                'verbose_name_plural': '匹配任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
