# Generated by Django 4.2.7 on 2025-09-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchingtask',
            name='heatmap_status',
            field=models.CharField(
                choices=[
                    ('not_started', '未开始'),
                    ('generating', '生成中'),
                    ('completed', '已完成'),
                    ('failed', '生成失败'),
                ],
                default='not_started',
                max_length=20,
                verbose_name='热力图状态'
            ),
        ),
        migrations.AddField(
            model_name='matchingtask',
            name='heatmap_data',
            field=models.JSONField(
                default=dict,
                verbose_name='热力图数据'
            ),
        ),
    ]
