# Generated by Django 4.2.16 on 2025-09-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20250920_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingtask',
            name='current_step',
            field=models.TextField(blank=True, verbose_name='当前步骤'),
        ),
    ]
