# Generated by Django 4.2.16 on 2025-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_type', models.CharField(choices=[('shoe_preview', '鞋模预览'), ('blank_preview', '粗胚预览'), ('heatmap', '匹配热图'), ('comparison', '对比视图')], max_length=20, verbose_name='内容类型')),
                ('object_id', models.PositiveIntegerField(verbose_name='对象ID')),
                ('cache_key', models.CharField(max_length=200, unique=True, verbose_name='缓存键')),
                ('html_content', models.TextField(verbose_name='HTML内容')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('access_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
            ],
            options={
                'verbose_name': '可视化缓存',
                'verbose_name_plural': '可视化缓存',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='visualizati_content_7e7c2b_idx'), models.Index(fields=['cache_key'], name='visualizati_cache_k_0464fb_idx'), models.Index(fields=['is_valid', 'expires_at'], name='visualizati_is_vali_c05074_idx')],
            },
        ),
    ]
