# Generated by Django 4.2.16 on 2025-09-15 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='鞋模名称')),
                ('file', models.FileField(upload_to='shoes/%Y/%m/', verbose_name='3DM文件')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='体积(mm³)')),
                ('bounding_box', models.JSONField(default=dict, verbose_name='边界框')),
                ('vertex_count', models.IntegerField(default=0, verbose_name='顶点数量')),
                ('face_count', models.IntegerField(default=0, verbose_name='面数量')),
                ('preview_html', models.TextField(blank=True, verbose_name='预览HTML')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='shoes/thumbnails/', verbose_name='缩略图')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '鞋模文件',
                'verbose_name_plural': '鞋模文件',
                'ordering': ['-created_at'],
            },
        ),
    ]
