# Generated by Django 4.2.16 on 2025-09-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoemodel',
            name='compression_ratio',
            field=models.FloatField(blank=True, help_text='相对于原始文件的压缩比例 (0.0-1.0)', null=True, verbose_name='压缩比'),
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='geometry_simplified',
            field=models.BooleanField(default=False, help_text='标记是否已生成简化的几何体', verbose_name='几何体已简化'),
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='lod_files',
            field=models.JSONField(blank=True, default=dict, help_text="存储不同精度级别的GLB文件路径 {'preview': 'path/to/low.glb', 'detail': 'path/to/mid.glb', 'full': 'path/to/high.glb'}", verbose_name='多精度文件路径'),
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='render_engine',
            field=models.CharField(choices=[('plotly', 'Plotly (传统)'), ('threejs', 'Three.js (优化)')], default='plotly', max_length=20, verbose_name='渲染引擎'),
        ),
        migrations.AddField(
            model_name='shoemodel',
            name='supports_webgl',
            field=models.BooleanField(default=False, help_text='标记是否已生成WebGL兼容的数据格式', verbose_name='支持WebGL渲染'),
        ),
    ]
