# Generated by Django 4.2.7 on 2025-08-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='任务ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='状态')),
                ('margin_distance', models.DecimalField(decimal_places=1, default=2.5, max_digits=3, verbose_name='余量距离')),
                ('result_data', models.JSONField(default=dict, verbose_name='匹配结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('shoe_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shoemodel', verbose_name='鞋模')),
            ],
            options={
                'verbose_name': '匹配任务',
                'verbose_name_plural': '匹配任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
