# Generated by Django 4.2.7 on 2025-08-16 02:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='blanks/', verbose_name='粗胚文件')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='体积(立方毫米)')),
                ('bounding_box', models.JSONField(default=dict, verbose_name='边界框信息')),
                ('key_features', models.JSONField(default=dict, verbose_name='关键特征')),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='材料成本(元)')),
                ('file_format', models.CharField(choices=[('3dm', 'Rhino 3DM'), ('mod', 'MOD格式')], max_length=10, verbose_name='文件格式')),
                ('points_count', models.IntegerField(default=0, verbose_name='点数量')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
            ],
            options={
                'verbose_name': '粗胚文件',
                'verbose_name_plural': '粗胚文件',
                'ordering': ['volume'],
            },
        ),
        migrations.CreateModel(
            name='ShoeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='shoes/', verbose_name='鞋模文件')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='体积(立方毫米)')),
                ('bounding_box', models.JSONField(default=dict, help_text='存储x_min, x_max, y_min, y_max, z_min, z_max', verbose_name='边界框信息')),
                ('key_features', models.JSONField(default=dict, help_text='存储几何特征向量和分析数据', verbose_name='关键特征')),
                ('file_format', models.CharField(choices=[('3dm', 'Rhino 3DM'), ('mod', 'MOD格式')], max_length=10, verbose_name='文件格式')),
                ('points_count', models.IntegerField(default=0, verbose_name='点数量')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('processing_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '鞋模文件',
                'verbose_name_plural': '鞋模文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operation', models.CharField(choices=[('upload', '文件上传'), ('parse', '文件解析'), ('analyze', '几何分析'), ('match', '匹配计算')], max_length=20, verbose_name='操作类型')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误')], default='info', max_length=10, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('extra_data', models.JSONField(default=dict, verbose_name='额外数据')),
                ('blank_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.blankmodel', verbose_name='关联粗胚')),
                ('shoe_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shoemodel', verbose_name='关联鞋模')),
            ],
            options={
                'verbose_name': '处理日志',
                'verbose_name_plural': '处理日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('margin_distance', models.DecimalField(decimal_places=1, default=2.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10.0)], verbose_name='余量距离(mm)')),
                ('similarity_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='几何相似度(%)')),
                ('material_utilization', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='材料利用率(%)')),
                ('average_margin', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='平均余量(mm)')),
                ('min_margin', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='最小余量(mm)')),
                ('max_margin', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='最大余量(mm)')),
                ('is_optimal', models.BooleanField(default=False, verbose_name='是否为最优匹配')),
                ('is_feasible', models.BooleanField(default=True, verbose_name='是否可行（满足余量要求）')),
                ('analysis_details', models.JSONField(default=dict, help_text='存储完整的几何分析和匹配数据', verbose_name='详细分析数据')),
                ('computation_time', models.FloatField(blank=True, null=True, verbose_name='计算耗时(秒)')),
                ('blank_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blankmodel', verbose_name='粗胚')),
                ('shoe_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shoemodel', verbose_name='鞋模')),
            ],
            options={
                'verbose_name': '匹配结果',
                'verbose_name_plural': '匹配结果',
                'ordering': ['-material_utilization', 'blank_model__volume'],
                'indexes': [models.Index(fields=['shoe_model', 'is_optimal'], name='core_matchi_shoe_mo_e154fb_idx'), models.Index(fields=['material_utilization'], name='core_matchi_materia_1865c1_idx'), models.Index(fields=['is_feasible'], name='core_matchi_is_feas_b34d5e_idx')],
                'unique_together': {('shoe_model', 'blank_model', 'margin_distance')},
            },
        ),
    ]
